import enum


class ProcedureCategory(enum.StrEnum):
    DIAGNOSTIC = "DIAGNOSTIC"
    PREVENTIVE = "PREVENTIVE"
    RESTORATIVE = "RESTORATIVE"
    ENDODONTICS = "ENDODONTICS"
    PERIODONTICS = "PERIODONTICS"
    PROSTHODONTICS_REMOVABLE = "PROSTHODONTICS_REMOVABLE"
    IMPLANTS = "IMPLANTS"
    PROSTHODONTICS_FIXED = "PROSTHODONTICS_FIXED"
    ORAL_SURGERY = "ORAL_SURGERY"
    ORTHODONTICS = "ORTHODONTICS"
    ADJUNCTIVE = "ADJUNCTIVE"
    UNKNOWN = "UNKNOWN"


class AgeStrategyType(enum.StrEnum):
    EXACT = "EXACT"
    CALENDAR_YEAR = "CALENDAR_YEAR"
    BENEFIT_YEAR_START = "BENEFIT_YEAR_START"
