import { Link, useNavigate } from "react-router-dom";

function MiniBar({ label, value, max, onClick }) { return <button type="button" onClick={onClick} className="group flex w-full items-center gap-3 text-left"><span className="w-28 truncate text-xs text-slate-600">{label}</span><span className="h-5 flex-1 overflow-hidden rounded bg-slate-100"><span className="block h-full rounded bg-indigo-500 group-hover:bg-indigo-600" style={{ width: `${Math.max(5, value / max * 100)}%` }} /></span><span className="w-6 text-right text-xs font-semibold">{value}</span></button>; }

export default function AnalyticsCharts({ claims }) {
  const navigate = useNavigate();
  const statuses = ["DRAFT", "SUBMITTED", "ACCEPTED", "REJECTED", "PAID"].map((status) => [status, claims.filter((claim) => claim.status === status).length]);
  const findingCounts = [["Documentation", 18], ["Financial", 13], ["Attachments", 8], ["Duplicate", 5]];
  const total = findingCounts.reduce((sum, [, value]) => sum + value, 0);
  return <div className="grid gap-5 xl:grid-cols-2">
    <section className="rounded-xl border bg-white p-5 shadow-sm" role="region" aria-labelledby="status-funnel-title"><h2 id="status-funnel-title" className="font-semibold">Status funnel</h2><div className="mt-4 space-y-3">{statuses.map(([status, value]) => <MiniBar key={status} label={status} value={value} max={Math.max(1, claims.length)} />)}</div></section>
    <section className="rounded-xl border bg-white p-5 shadow-sm" role="region" aria-labelledby="clean-rate-title"><h2 id="clean-rate-title" className="font-semibold">First-pass clean rate</h2><p className="mt-1 text-sm text-slate-500">Last 8 weeks</p><div className="mt-6 flex h-28 items-end gap-2" role="img" aria-label="Bar chart showing clean rate over last 8 weeks, increasing from 71% to 86%">{[71, 74, 69, 78, 80, 77, 84, 86].map((value, index) => <div key={index} title={`${value}%`} className="flex flex-1 flex-col justify-end"><span className="rounded-t bg-emerald-500" style={{ height: `${value}%` }} /><small className="mt-1 text-center text-[10px] text-slate-500">W{index + 1}</small></div>)}</div></section>
    <section className="rounded-xl border bg-white p-5 shadow-sm" role="region" aria-labelledby="top-findings-title"><div className="flex items-center justify-between"><div><h2 id="top-findings-title" className="font-semibold">Top findings</h2><p className="text-sm text-slate-500">Click a bar to review affected claims.</p></div><Link to="/claims" className="text-sm text-indigo-700 underline">All claims</Link></div><div className="mt-4 space-y-3">{[["Narrative required", 14], ["Fee exceeds allowed", 11], ["Radiograph required", 8], ["Line total mismatch", 6], ["Pre-authorisation", 5]].map(([label, value]) => <MiniBar key={label} label={label} value={value} max={14} onClick={() => navigate('/claims')} />)}</div></section>
    <section className="rounded-xl border bg-white p-5 shadow-sm" role="region" aria-labelledby="category-findings-title"><h2 id="category-findings-title" className="font-semibold">Findings by category</h2><div className="mt-5 flex items-center gap-6"><div className="grid h-32 w-32 place-items-center rounded-full" role="img" aria-label={`Pie chart of findings by category. Total findings: ${total}`} style={{ background: 'conic-gradient(#4f46e5 0 41%, #f59e0b 41% 70%, #ef4444 70% 89%, #64748b 89% 100%)' }}><div className="grid h-20 w-20 place-items-center rounded-full bg-white text-sm font-bold">{total}</div></div><div className="space-y-2">{findingCounts.map(([label, value]) => <p key={label} className="text-sm text-slate-600"><span className="font-semibold text-slate-900">{value}</span> {label}</p>)}</div></div></section>
  </div>;
}
