import { useMemo, useState } from "react";

const rules = [
  ["RADIOGRAPH_REQUIRED", "Documentation", "ERROR", "Add a radiograph attachment", 128], ["NARRATIVE_REQUIRED", "Documentation", "ERROR", "Add a clinical narrative", 96], ["PRE_AUTHORISATION_REQUIRED", "Documentation", "ERROR", "Enter an authorisation number", 73], ["UNSUPPORTED_ATTACHMENT_TYPE", "Attachments", "ERROR", "Replace with PDF, JPEG, or PNG", 31], ["ATTACHMENT_SIZE_LIMIT", "Attachments", "ERROR", "Compress or replace attachment", 19], ["LINE_FEES_DO_NOT_SUM_TO_TOTAL", "Financial", "ERROR", "Set total to line-fee sum", 62], ["NON_POSITIVE_FEE", "Financial", "ERROR", "Enter a positive fee", 14], ["FEE_EXCEEDS_ALLOWED_AMOUNT", "Financial", "WARNING", "Use allowed amount", 84], ["LIKELY_DUPLICATE_CLAIM", "Duplicate", "WARNING", "Review matching claim", 22],
].map(([code, category, severity, fixture, hits]) => ({ code, category, severity, fixture, hits }));

export default function RulesAdmin() {
  const [query, setQuery] = useState(""); const [category, setCategory] = useState(""); const [severity, setSeverity] = useState(""); const [selected, setSelected] = useState(rules[0]); const [enabled, setEnabled] = useState(true); const [simulation, setSimulation] = useState(null);
  const filtered = useMemo(() => rules.filter((rule) => (!query || rule.code.toLowerCase().includes(query.toLowerCase())) && (!category || rule.category === category) && (!severity || rule.severity === severity)), [query, category, severity]);
  return <div className="space-y-6"><div><p className="text-xs font-semibold uppercase tracking-widest text-slate-500">Administration</p><h1 className="mt-1 text-3xl font-bold">Rules catalogue</h1></div><div className="grid gap-6 xl:grid-cols-[minmax(0,1fr)_360px]"><section className="rounded-xl border bg-white shadow-sm"><div className="grid gap-3 border-b p-4 md:grid-cols-3"><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search rule code" className="rounded border px-3 py-2 text-sm" /><select value={category} onChange={(event) => setCategory(event.target.value)} className="rounded border px-3 py-2 text-sm"><option value="">All categories</option>{[...new Set(rules.map((rule) => rule.category))].map((item) => <option key={item}>{item}</option>)}</select><select value={severity} onChange={(event) => setSeverity(event.target.value)} className="rounded border px-3 py-2 text-sm"><option value="">All severities</option><option>ERROR</option><option>WARNING</option></select></div><div className="divide-y">{filtered.map((rule) => <button key={rule.code} type="button" onClick={() => { setSelected(rule); setEnabled(true); }} className="flex w-full items-center justify-between px-4 py-3 text-left hover:bg-slate-50"><span><span className="font-mono text-sm font-semibold">{rule.code}</span><span className="ml-2 text-xs text-slate-500">{rule.category}</span></span><span className={rule.severity === "ERROR" ? "text-xs font-bold text-red-600" : "text-xs font-bold text-amber-600"}>{rule.severity}</span></button>)}</div></section><aside className="rounded-xl border bg-white p-5 shadow-sm"><p className="font-mono text-sm font-bold">{selected.code}</p><p className="mt-3 text-sm text-slate-600">Definition: validates claim data against the organisation's configured {selected.category.toLowerCase()} policy.</p><div className="mt-4 rounded bg-slate-50 p-3"><p className="text-xs font-semibold uppercase text-slate-500">Fixtures</p><p className="mt-1 text-sm">{selected.fixture}</p></div><p className="mt-4 text-sm"><strong>{selected.hits}</strong> hits in the last 90 days</p><label className="mt-4 flex items-center gap-2 text-sm"><input type="checkbox" checked={enabled} onChange={(event) => setEnabled(event.target.checked)} /> Enabled <span className="text-xs text-slate-500">(admin only)</span></label><button type="button" onClick={() => setSimulation({ checked: 24, matched: Math.max(1, Math.round(selected.hits / 9)), runAt: new Date().toLocaleTimeString() })} className="mt-5 rounded bg-slate-900 px-3 py-2 text-sm font-semibold text-white">Run simulation</button>{simulation && <div className="mt-3 rounded border border-emerald-200 bg-emerald-50 p-3 text-sm text-emerald-900"><strong>Simulation complete</strong><br />Checked {simulation.checked} representative claims; {simulation.matched} would receive this finding.<br /><span className="text-xs">Run at {simulation.runAt}</span></div>}</aside></div></div>;
}
